# This pipeline demonstrates how to build directly in a Windows VM
name: PipelineBuildingInWindowsVM
trigger: none

parameters:
- name: poolName
  type: string
  default: pt-github-test-pool

- name: image
  type: string
  default: pt-validation-dev-windows2022

- name: os
  type: string
  default: windows

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: ${{ parameters.poolName }}
      image: ${{ parameters.image }}
      os: ${{ parameters.os }}
    stages:
    - stage: stage
      displayName: Building in a Windows VM
      jobs:
      - job: job
        displayName: Job
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)
            artifactName: myPipelineArtifact
        steps:
        - powershell: echo "Hello World from Job"
        - checkout: self
